In [1]:
import h5py
import numpy as np

file_path = "test_data.hdf5"

with h5py.File(file_path, "r") as f:
    # high_count data
    high_data = f["/high_count/data"][:]          # Shape (3034, 240, 192)
    high_monitor = f["/high_count/monitor"][:]    # Shape (3034,)
    high_sampling = f["/high_count/sampling_time"][:]

    # low_count data
    low_data = f["/low_count/data"][:]            # Shape (3034, 240, 192)
    low_monitor = f["/low_count/monitor"][:]
    low_sampling = f["/low_count/sampling_time"][:]

print("High count data:", high_data.shape)
print("Low count data:", low_data.shape)

for i in range(1):
    print(f"Sample {i}:")
    print(high_data[i])   # das ist ein 240x192-Array
    print()               # Leerzeile
    print(low_data[i])    # das ist ein 240x192-Array

High count data: (192, 240, 3034)
Low count data: (192, 240, 3034)
Sample 0:
[[233. 276. 253. ... 314. 286. 333.]
 [301. 262. 282. ... 297. 324. 342.]
 [293. 291. 275. ... 343. 334. 346.]
 ...
 [292. 270. 292. ... 334. 308. 310.]
 [325. 340. 321. ... 292. 309. 312.]
 [291. 286. 277. ... 298. 321. 312.]]

[[ 3.  3.  0. ... 16. 19. 13.]
 [ 1.  3.  1. ... 15. 20. 18.]
 [ 0.  3.  2. ... 14. 10. 17.]
 ...
 [ 1.  3.  3. ... 13. 21. 15.]
 [ 2.  5.  3. ... 21. 13. 20.]
 [ 1.  3.  2. ... 13. 12. 19.]]
